/*CREACION DE ESQUEMAS.*/
DROP SCHEMA IF EXISTS `wop`;
/*BAM.*/
CREATE SCHEMA `wop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
 USE `wop`;

SET NAMES utf8 ;
SET character_set_client = utf8mb4 ;


CREATE TABLE `WORK_ORDER` (
  `ID` integer NOT NULL AUTO_INCREMENT,
  `REFERENCEPREFIX`	varchar(20), -- 1: EXT  3:DUP
  `REFERENCENUMBER` varchar(20),
	`STATUS` varchar(2), --  (2,4,6,8)  2:init  4:apda  6:CANCELADO
	`WORKORDERTYPE` integer, -- (1,11,21,25)
	`PLACEID` integer, -- install_place.placeid
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `WORK_ORDER` VALUES (1,'1','105991001',1,2,1);
INSERT INTO `WORK_ORDER` VALUES (2,'1','805982010',2,4,2);
INSERT INTO `WORK_ORDER` VALUES (3,'3','105982002',4,11,3);
INSERT INTO `WORK_ORDER` VALUES (4,'1','805982011',2,4,4);


CREATE TABLE `WO_DEVICE` (
  `ID` integer NOT NULL AUTO_INCREMENT,
  `WORKORDER` integer,
  `TARGETID` varchar(20), -- 'ENEL_CMEC_METER'
  `SERIAL` varchar(40),    
  PRIMARY KEY (`ID`),
  KEY `FK_workorder_id` (`WORKORDER`),
  CONSTRAINT `FK_workorder_id` FOREIGN KEY (`WORKORDER`) REFERENCES `WORK_ORDER` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `WO_DEVICE` VALUES (1,1,'ENEL_CMEC_METER','02456789QYF');
INSERT INTO `WO_DEVICE` VALUES (2,2,'ENEL_CMEC_METER','WAT-014867i89');
INSERT INTO `WO_DEVICE` VALUES (3,3,'ENEL_CMEC_METER',null); -- '245YW678900');
INSERT INTO `WO_DEVICE` VALUES (4,4,'ENEL_CMEC_METER','WAT-024867i89');


	
CREATE TABLE `WO_DEV_OPERATION` (
  `ID` integer NOT NULL AUTO_INCREMENT,
  `WORKORDER` integer,
  `OPERATIONNAME` varchar(40), -- 'PULSE_WATERMETER_CONNECT'
  `ARGNAME` varchar(100), -- 'PULSE_WATERMETER_CONNECT.CONNECTED_PORT_ID'
  PRIMARY KEY (`ID`),KEY `FK_devop_workorder_id` (`WORKORDER`),
  CONSTRAINT `FK_devop_workorder_id` FOREIGN KEY (`WORKORDER`) REFERENCES `WORK_ORDER` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `WO_DEV_OPERATION` VALUES (1,1,'PULSE_WATERMETER_CONNECT','PULSE_WATERMETER_CONNECT.CONNECTED_PORT_ID');	
INSERT INTO `WO_DEV_OPERATION` VALUES (2,2,'PULSE_WATERMETER_CONNECT','PULSE_WATERMETER_CONNECT.CONNECTED_PORT_ID');	
INSERT INTO `WO_DEV_OPERATION` VALUES (3,3,'PULSE_WATERMETER_CONNECT','PULSE_WATERMETER_CONNECT.CONNECTED_PORT_ID');	
INSERT INTO `WO_DEV_OPERATION` VALUES (4,4,'PULSE_WATERMETER_CONNECT','PULSE_WATERMETER_CONNECT.CONNECTED_PORT_ID');	

CREATE TABLE `OPN_ARG_VALUE` (
  `ID` integer NOT NULL AUTO_INCREMENT,  	
  `ARGVALUE` varchar(20),
  `WODEVOPERATION` integer, -- WO_DEV_OPERATION.id
  `ARGNAME` varchar(90),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `OPN_ARG_VALUE` VALUES (1,'1',1,'');
INSERT INTO `OPN_ARG_VALUE` VALUES (2,'2',2,'PULSE_WATERMETER_CONNECT.CONNECTED_PORT_ID');
INSERT INTO `OPN_ARG_VALUE` VALUES (3,'3',3,'');
INSERT INTO `OPN_ARG_VALUE` VALUES (4,'4',4,'PULSE_WATERMETER_CONNECT.CONNECTED_PORT_ID');

