/*CREACION DE ESQUEMAS.*/
DROP SCHEMA IF EXISTS `bam`;
/*BAM.*/
CREATE SCHEMA `bam` DEFAULT CHARACTER SET utf8mb4  COLLATE utf8mb4_general_ci;
 USE `bam`;

SET NAMES utf8 ;
SET character_set_client = utf8mb4 ;


CREATE TABLE `PERSON` (
  `ID` integer NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` varchar(50),
  `LASTNAME` varchar(40),  
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `PERSON` VALUES (1,'Crow´s Nest','Pub');
INSERT INTO `PERSON` VALUES (2,'Actea','Cilia');
INSERT INTO `PERSON` VALUES (3,'Malcolm','Galea');
INSERT INTO `PERSON` VALUES (4,'Christian','Galea');


CREATE TABLE `ADDRESS` (
  `ID` integer NOT NULL AUTO_INCREMENT,
  `STREET` varchar(50),
  `NUMBER` varchar(10),
  `HOUSENAME` varchar(50),
  `CITY` varchar(50),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `ADDRESS` VALUES (1,'Triq Spinola','55','Pub','St. Julians');
INSERT INTO `ADDRESS` VALUES (2,'Il-Knisja','1','Restaurant','St. Julians');
INSERT INTO `ADDRESS` VALUES (3,'St. George`s','7','House','Il-Belt Valletta');
INSERT INTO `ADDRESS` VALUES (4,'St. George`s','55','Flat1','Il-Belt Valletta');

CREATE TABLE `INSTALL_PLACE` (
  `ID` integer NOT NULL AUTO_INCREMENT,
  `PLACEID` integer,
  `ADDRESS` integer,
  `CONTACT` integer,
  PRIMARY KEY (`ID`),
  KEY `FK_contact_id` (`CONTACT`),
  CONSTRAINT `FK_contact_id` FOREIGN KEY (`CONTACT`) REFERENCES `PERSON` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE,
  KEY `FK_address_id` (`ADDRESS`),
  CONSTRAINT `FK_address_id` FOREIGN KEY (`ADDRESS`) REFERENCES `ADDRESS` (`ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `INSTALL_PLACE` VALUES (1,1,1,1);
INSERT INTO `INSTALL_PLACE` VALUES (2,2,2,2);
INSERT INTO `INSTALL_PLACE` VALUES (3,3,3,3);
INSERT INTO `INSTALL_PLACE` VALUES (4,4,4,4);

CREATE TABLE `INSTALL_POINT` (
  `ID` integer NOT NULL AUTO_INCREMENT,
  `INSTALLPLACE` integer,
  `POINTOFDELIVERY` VARCHAR(20),
  `NETWORK` integer,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `INSTALL_POINT` VALUES (1,1,'PD_1',1);
INSERT INTO `INSTALL_POINT` VALUES (2,2,'PD_2',2);
INSERT INTO `INSTALL_POINT` VALUES (3,3,'PD_3',1);
INSERT INTO `INSTALL_POINT` VALUES (4,4,'PD_4',2);

CREATE TABLE `ASSET` (
  `ID` integer NOT NULL AUTO_INCREMENT,
  `INSTALLPOINT` integer,
  `SERIAL` varchar(40),  
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
INSERT INTO `ASSET` VALUES (1,1,'02456789QYF');
INSERT INTO `ASSET` VALUES (2,2,'55W14867i89');
INSERT INTO `ASSET` VALUES (3,3,'245YW678900');
INSERT INTO `ASSET` VALUES (4,4,'WAT-024867i89');
